copotrzebne-pl/copotrzebne-api

.github/workflows/main.yml, .github/workflows/release.yml, Procfile, README.md, app.json
The initial version of deployment.
I've assumed that we are pushing code to Heroku using [GIT approach](https://devcenter.heroku.com/articles/git).
Do you have any opinion about Docker? If you prefer this way, I can change it.
[GitHub Actions](https://docs.github.com/en/actions) are used for CI/CD - free for Public projects. You can find output from tests here https://github.com/copotrzebne-pl/copotrzebne-api/actions
Let's agree here too if we want to use any staging environment or we are pushing directly to PRO :)
=> Deployment

.eslintrc.js, README.md, package.json, src/app.module.ts, src/config/database/sequelize.config.js, src/places/models/place.model.ts, src/places/places.controller.ts, test/places.e2e-spec.ts, yarn.lock
Just added commands for better handling db & sequelize migrations.
=> chore: sequelize setup

README.md, src/places/places.controller.ts, src/places/places.service.ts
=> feat: transaction management

Dockerfile, docker-compose.db.yml, docker-compose.yml
Run app using docker-compose:
```sh
docker-compose --env-file .env -f docker-compose.yml -f docker-compose.db.yml up --build
```
=> feat: add docker compose for app, update node.js in container

migrations/20220313175342-update-user.js, src/users/dto/create-user.dto.ts, src/users/models/user.model.ts, src/users/types/user-role.enum.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
Endpoint for creating a user as admin
=> feat(users): create user endpoint

src/config/database/database.config.ts
https://help.heroku.com/QD1AIH8R/how-do-i-use-sequelize-to-connect-to-heroku-postgres
=> chore: Fix connection to DB on Heroku

src/places/places.controller.ts, src/users/users.service.ts
Update hardcoded ID with actual session user id
=> fix: repair owned places endpoint

src/demands/demands.controller.ts, src/demands/services/demands.service.ts, src/places/places.controller.ts, src/places/services/places.service.ts, src/priorities/priorities.controller.ts, src/supplies/services/supplies.service.ts, src/supplies/supplies.controller.ts
New routes:
- GET `/supplies/:id` - gets supply by id
- GET `/demands/:id` - gets demand by id
- GET `/places/:id` - gets place by id
Plus controllers refactoring.
=> feat: find by id routes

src/demands/demands.controller.ts, src/demands/services/demands.service.ts
- DELETE `/demands/:id` - deletes single demand
=> feat: delete route for demand

src/places/controllers/places.controller.spec.ts, src/places/controllers/places.controller.ts, src/places/controllers/users-places.controller.ts, src/places/places.module.ts, src/users/users.controller.ts
GET /api/places/owned ->  /api/users-places/owned
POST /users/:userId/assign-place/:placeId   -> /users-places/:userId/assign-place/:placeId
DELETE /users/:userId/assign-place/:placeId   ->  /users-places/:userId/assign-place/:placeId
=> refactor users-places routes

src/places/models/places.model.ts, src/places/services/places.service.ts
Added `lastUpdatedAt` field to:
- `/places/:id`
- `/places/owned/:userId`
=> feat: add lastUpdatedAt field to all place queries

migrations/20220324070441-pluralize-user-place-table.js, src/authentication/authentication.controller.spec.ts, src/authentication/authentication.service.spec.ts, src/categories/categories.controller.ts, src/config/database/database.config.ts, src/places/models/places.model.ts, src/users/models/user-place.model.ts, src/users/models/user.model.ts, src/users/users.module.ts, src/users/users.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/45
=> fix: change user_place table name to users_places

src/categories/categories.controller.ts, src/demands/demands.controller.spec.ts, src/demands/demands.controller.ts, src/demands/demands.module.ts, src/places/controllers/places.controller.ts, src/places/controllers/users-places.controller.ts, src/places/places.module.ts, src/places/services/places.service.ts, src/users/users.controller.ts
=> improve authorization - closes #44

src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/54
=> feat: sort places by lastUpdatedAt

migrations/20220318113850-create-categories.js, migrations/20220331135318-add-place-working-hours.js, src/places/dto/create-place.dto.ts, src/places/dto/update-place.dto.ts, src/places/models/place.model.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/56
=> feat: add working hours for place

src/places/controllers/places.controller.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/62
=> feat: find places with supply

src/places/controllers/places.controller.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/64
=> feat: delete place by id

src/demands/services/demands.service.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/68
=> feat: add associated entities to response after creation of demand

src/places/controllers/places.controller.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/66
=> feat: search by multiple supplies

src/places/models/place.model.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/81
=> fix: calculate slug in methods instead of model setter

src/demands/services/demands.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/79
Test plan:
1. Update demand
2. Response after update should contain demand with priority, supply and supply category
=> feat: return detailed demand after update

migrations/20220405075412-add-priority-importance.js, src/error/error-handler.ts, src/error/forbidden-operation.error.ts, src/places/models/place.model.ts, src/places/services/places.service.ts, src/priorities/models/priority.model.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/87
New virtual field `priority `on `places` which is calculated from place `demands` priorities. The value is a number which corresponds with `importance` column in `priorities` table. If there's no demands for place, 0 is returned.
=> feat: place priority

src/places/controllers/places.controller.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/96
`GET /places/name-slug/:nameSlug`
=> feat: search place by name slug

src/places/controllers/places.controller.ts, src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/98
- [Added] `POST places/draft` (everyone) - it will create place in inactive state
- [Changed] `POST places/` (admin) - changed behaviour to create place in active state
=> feat: add endpoint to create place draft

src/places/services/places.service.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/104
=> feat: sort places by prio

src/interceptors/cache-header.interceptor.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/112
=> feat: add vary header and change cache-control to no-store

migrations/20220419191258-add-places-bank-account.js, src/places/dto/create-place.dto.ts, src/places/dto/update-place.dto.ts, src/places/models/place.model.ts, src/tests/places/controllers/get-place-by-id.e2e-spec.ts, src/tests/places/controllers/get-places.e2e-spec.ts, src/tests/places/controllers/patch-place.e2e-spec.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/121
=> feat: add place bank account

.github/workflows/deploy-dev.yml, README.md
Is working well on https://dev.copotrzebne.pl/
=> chore: Migration to one Convox rack

migrations/20220502201039-add-place-bank-account-desc-and-resources.js, migrations/20220502201039-add-place-bank-info-and-resources.js, src/places/dto/create-place.dto.ts, src/places/dto/update-place.dto.ts, src/places/models/place.model.ts, src/tests/places/controllers/get-place-by-id.e2e-spec.ts, src/tests/places/controllers/get-places.e2e-spec.ts, src/tests/places/controllers/patch-place.e2e-spec.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/137
=> feat: add place resources

migrations/20220508202917-make-public-announcements-title-nullable.js, src/announcements/dto/create-public-announcement.dto.ts, src/announcements/models/public-announcement.model.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/149
=> feat: make public announcement title nullable

src/demands/services/demands.service.ts, src/demands/types/demands-sort-options.type.enum.ts, src/demands/types/sort.type.enum.ts, src/places/controllers/places.controller.ts
=> feat: sort place's demands by date

migrations/20220522113723-add-moderator-role.js, src/announcement-comments/announcement-comments.controller.ts, src/announcements/controllers/announcements.controller.ts, src/demands/demands.controller.ts, src/places/controllers/places.controller.ts, src/tests/places/controllers/delete-place.e2e-spec.ts, src/tests/places/controllers/patch-place.e2e-spec.ts, src/users/types/user-role.enum.ts, src/users/users.controller.ts
Related to: https://github.com/copotrzebne-pl/copotrzebne-api/issues/160
=> feat: add moderator role

src/places/controllers/places.controller.ts
=> docs: fix swagger annotation for getting demands for place
